//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shipper", Namespace="http://schemas.datacontract.org/2004/07/NorthwindService")]
    public partial class Shipper : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CompanyNameField;
        
        private string PhoneField;
        
        private int ShipperIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipperID
        {
            get
            {
                return this.ShipperIDField;
            }
            set
            {
                this.ShipperIDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="EC.WCFLABB3", ConfigurationName="IShipperService")]
public interface IShipperService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="EC.WCFLABB3/IShipperService/GetShipperByID", ReplyAction="EC.WCFLABB3/IShipperService/GetShipperByIDResponse")]
    NorthwindService.Shipper GetShipperByID(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="EC.WCFLABB3/IShipperService/GetShipperByID", ReplyAction="EC.WCFLABB3/IShipperService/GetShipperByIDResponse")]
    System.Threading.Tasks.Task<NorthwindService.Shipper> GetShipperByIDAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="EC.WCFLABB3/IShipperService/SaveShipper", ReplyAction="EC.WCFLABB3/IShipperService/SaveShipperResponse")]
    void SaveShipper(int id, string companyName, string phone);
    
    [System.ServiceModel.OperationContractAttribute(Action="EC.WCFLABB3/IShipperService/SaveShipper", ReplyAction="EC.WCFLABB3/IShipperService/SaveShipperResponse")]
    System.Threading.Tasks.Task SaveShipperAsync(int id, string companyName, string phone);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IShipperServiceChannel : IShipperService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ShipperServiceClient : System.ServiceModel.ClientBase<IShipperService>, IShipperService
{
    
    public ShipperServiceClient()
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ShipperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public NorthwindService.Shipper GetShipperByID(int id)
    {
        return base.Channel.GetShipperByID(id);
    }
    
    public System.Threading.Tasks.Task<NorthwindService.Shipper> GetShipperByIDAsync(int id)
    {
        return base.Channel.GetShipperByIDAsync(id);
    }
    
    public void SaveShipper(int id, string companyName, string phone)
    {
        base.Channel.SaveShipper(id, companyName, phone);
    }
    
    public System.Threading.Tasks.Task SaveShipperAsync(int id, string companyName, string phone)
    {
        return base.Channel.SaveShipperAsync(id, companyName, phone);
    }
}
